### ISSUE TITLE
pivotal_agent doesn't work anymore

### ISSUE THREAD

**Issue by 4z3** [zalora/microgram#48]
Running `pivotal_agent` fails with

```
/nix/store/a457ywa1haa0sgr9g7a1pgldrg3s798d-coreutils-8.24/bin/env: ruby: No such file or direct
```

After providing ruby via `PATH` it will fail with

```
/nix/store/54i45grx43zdnsv2m0jwkf1svk7f8kbk-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find multipart-post-2.0.0 in any of the sources (Bundler::GemNotFound)
    from /nix/store/54i45grx43zdnsv2m0jwkf1svk7f8kbk-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib/bundler/spec_set.rb:85:in `map!'
    from /nix/store/54i45grx43zdnsv2m0jwkf1svk7f8kbk-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib/bundler/spec_set.rb:85:in `materialize'
    from /nix/store/54i45grx43zdnsv2m0jwkf1svk7f8kbk-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib/bundler/definition.rb:140:in `specs'
    from /nix/store/54i45grx43zdnsv2m0jwkf1svk7f8kbk-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib/bundler/definition.rb:185:in `specs_for'
    from /nix/store/54i45grx43zdnsv2m0jwkf1svk7f8kbk-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib/bundler/definition.rb:174:in `requested_specs'
    from /nix/store/54i45grx43zdnsv2m0jwkf1svk7f8kbk-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib/bundler/environment.rb:18:in `requested_specs'
    from /nix/store/54i45grx43zdnsv2m0jwkf1svk7f8kbk-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:13:in `setup'
    from /nix/store/54i45grx43zdnsv2m0jwkf1svk7f8kbk-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib/bundler.rb:127:in `setup'
    from /nix/store/54i45grx43zdnsv2m0jwkf1svk7f8kbk-bundler-1.10.5/lib/ruby/gems/2.2.2/gems/bundler-1.10.5/lib/bundler/setup.rb:18:in `<top (required)>'
    from /nix/store/nia1vryz5z8jzbaqib4fxqzcz6fwz431-rubygems-2.4.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /nix/store/nia1vryz5z8jzbaqib4fxqzcz6fwz431-rubygems-2.4.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by proger** [comment]
Looks like the commit message was too ambiguous.
